### ISSUE TITLE
Vue User Profile

### ISSUE THREAD

**Issue by besnikh** [auth0-samples/auth0-vue-samples#18]
Can someone help me on how to fetch user profile after they signed up to display that profile info into users profile page ? 

There are some examples using react and other frameworks but none using Vue 2

Thnx in advance!

**Comment by alex-webb** [comment]
I would also like to know this.  I tried adding 

`this.auth0.client.userInfo(authResult.accessToken, function (err, user) {
          localStorage.setItem('user_details', user)
          console.log(user)
          console.log(err)
        })`

inside the handleAuthentication () method about line 35 but I don't get any data back.

**Comment by elkdanger** [comment]
Hey @besnikh and @alex-webb,

I know this issue is old; the sample has been updated since the issue was raised and should (hopefully!) show much more clearly how to gain access to the user's profile information.

I'll close this for now, but if you're still having trouble, feel free to raise another issue or re-open this one to continue the discussion.
