### ISSUE TITLE
Error component issues

### ISSUE THREAD

**Issue by uandco** [auth0-samples/auth0-vue-samples#89]
Hi,

The error component uses `{{msg}}` but `msg()` is declared as a method. I believe it should be a computed value, like `show`

**Comment by stevehobbsdev** [comment]
@uandco Initially I thought you were dead right, so I raised a PR to fix it, but I think on reflection it's better the other way around. `show` should probably be a method rather than a computed property. The reason being, neither `show` nor `msg` depend on any props or data, so there's nothing to react to.

In short, I think `show` would be better off as a method rather than a computed prop - so opposite to what you propose. What do you think?

**Comment by uandco** [comment]
@stevehobbsdev according to https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods it is better to use computed values than calling the methods from the template.

`show` and `msg` both depend on `this.$auth.error`, they could potentially react to what happens within the auth plugin? Not sure if the `error` property can change later tho.

Ultimately, you could use a single property since you only want to show the error when it's a readable string. It doesn't really need to be not null, and a falsy would work imho. So, basically, use `v-if="msg"` and `{{ msg }}`, and get rid of `show`.

**Comment by stevehobbsdev** [comment]
>  it is better to use computed values than calling the methods from the template

It really depends on the use-case.

`error` will change from having no value to having a value if an error occurs. Whether it can change back again depends on whether you're using popup mode or not. But that has revealed another problem in that `loginWithPopup` never sets the error value - will fix this.

I think in this scenario using a computed prop would be more appropriate, so I'll re-issue that PR (along with the above fix).

> you could use a single property since you only want to show the error when it's a readable string

You're right there, too - I'll change this as well. Thanks for raising these issues!
